Repository Codebrahma/react-lite-ui, pull requests merged in 2018-11, with the labels that each got.

#130 Navbar design
  docs/client/components/common/DefaultCode/Navbar/index.js
  docs/client/components/common/DefaultCode/Navbar/style.scss
  docs/client/components/common/DefaultCode/theme.scss
  package-lock.json
  src/globals/fonts.scss
  src/index.js
  src/navbar/index.js
  src/navbar/tests/render.test.js
  src/navbar/theme.scss
Labels: :art: design-update

#134 Table component
  docs/client/components/common/DefaultCode/Table/index.js
  docs/client/components/common/DefaultCode/index.js
  docs/client/components/common/componentList.js
  src/globals/_theme.scss
  src/index.js
  src/table/index.js
  src/table/readMe.md
  src/table/theme.scss
Labels: :dart: 1.X Target

#143 Carousel tests
  src/carousel/index.js
  src/carousel/tests/accessibility.test.js
  src/carousel/tests/render.test.js
Labels: :dart: 1.X Target

#144 Progressbar tests
  src/progressbar/index.js
  src/progressbar/tests/accessibility.test.js
  src/progressbar/tests/render.test.js
Labels: :dart: 1.X Target

#122 update modal design
  docs/client/components/common/DefaultCode/Modal/index.js
  src/modal/index.js
  src/modal/readMe.md
  src/modal/tests/accessibility.test.js
  src/modal/theme.scss
Labels: :art: design-update

#164 Navbar fix
  docs/client/index.js
  docs/webpack.config.development.js
  docs/webpack.config.production.js
  package-lock.json
  src/globals/fonts/PTSans/cyrillic-ext.woff2
  src/globals/fonts/PTSans/cyrillic.woff2
  src/globals/fonts/PTSans/index.scss
  src/globals/fonts/PTSans/latin-ext.woff2
  src/globals/fonts/PTSans/latin.woff2
  src/globals/fonts/Roboto/cyrillic-ext.woff2
  src/globals/fonts/Roboto/cyrillic.woff2
  src/globals/fonts/Roboto/greek-ext.woff2
  src/globals/fonts/Roboto/greek.woff2
  src/globals/fonts/Roboto/index.scss
  src/globals/fonts/Roboto/latin-ext.woff2
  src/globals/fonts/Roboto/latin.woff2
  src/globals/fonts/Roboto/vietnamese.woff2
  src/index.js
  src/navbar/index.js
  src/navbar/theme.scss
  webpack.common.js
Labels: :bug: bug, :construction: WIP
