Repository Codebrahma/react-lite-ui, pull requests merged in 2018-10, with the labels that each got.

#76 test(snackbar/tests): add tests for snackbar
  src/snackbar/index.js
  src/snackbar/tests/render.test.js
Labels: WIP

#86 Mixins
  src/autocomplete/theme.scss
  src/avatar/theme.scss
  src/badge/theme.scss
  src/globals/_mixins.scss
Labels: question

#100 Avatar design
  docs/client/components/common/DefaultCode/Avatar/index.js
  src/avatar/index.js
  src/avatar/readMe.md
  src/avatar/theme.scss
Labels: :art: design-update

#99 fix(src/checkbox): update design and add inverted prop
  src/checkbox/index.js
  src/checkbox/theme.scss
Labels: :art: design-update

#98 feat(src/card): update design, add expand action
  src/card/index.js
  src/card/theme.scss
Labels: :art: design-update

#96 fix(src/autocomplete): add input animation and auto-fill options for …
  src/autocomplete/index.js
  src/autocomplete/theme.scss
  src/globals/_theme.scss
  src/globals/animations.scss
Labels: :art: design-update

#88 TextInput from design
  docs/client/components/common/DefaultCode/TextInput/index.js
  src/textInput/index.js
  src/textInput/theme.scss
Labels: :art: design-update

#118 Carousel
  docs/client/components/common/DefaultCode/Carousel/index.js
  docs/client/components/common/DefaultCode/index.js
  docs/client/components/common/componentList.js
  docs/package-lock.json
  docs/package.json
  docs/webpack.config.development.js
  docs/webpack.config.production.js
  package-lock.json
  package.json
  src/carousel/carouselItem.js
  src/carousel/index.js
  src/carousel/readMe.md
  src/carousel/theme.scss
  src/globals/fonts.scss
  src/globals/left-arrow.woff
  src/index.js
  webpack.common.js
Labels: 1.X Target

#116 fix(src/multiselect): update design
  src/multiselect/index.js
  src/multiselect/tests/accessibility.test.js
  src/multiselect/tests/render.test.js
  src/multiselect/theme.scss
Labels: :art: design-update

#109 Popover
  docs/client/components/common/DefaultCode/Popover/index.js
  docs/client/components/common/DefaultCode/index.js
  docs/client/components/common/componentList.js
  src/index.js
  src/popover/index.js
  src/popover/readMe.md
  src/popover/theme.scss
Labels: 1.X Target

#120 Radio Button Group Deesign
  src/radioButtonGroup/theme.scss
Labels: :art: design-update

#125 ✨ add progressbar component
  docs/client/components/common/DefaultCode/ProgressBar/index.js
  docs/client/components/common/DefaultCode/index.js
  docs/client/components/common/componentList.js
  src/globals/_theme.scss
  src/index.js
  src/progressbar/index.js
  src/progressbar/readMe.md
  src/progressbar/theme.scss
Labels: 1.X Target

#129 Button size from design
  docs/client/components/common/DefaultCode/Popover/index.js
  src/button/index.js
  src/button/theme.scss
Labels: :art: design-update, :bug: bug

#121 💄 update drawer design
  src/drawer/theme.scss
Labels: :art: design-update

#110 Slider component
  docs/client/components/common/DefaultCode/Slider/index.js
  docs/client/components/common/DefaultCode/index.js
  docs/client/components/common/componentList.js
  src/index.js
  src/slider/index.js
  src/slider/readMe.md
  src/slider/theme.scss
Labels: 1.X Target
