Repository Codebrahma/react-lite-ui, pull requests merged in 2018-12, with the labels that each got.

#172 Navbar improvements and fixes
  docs/package-lock.json
  package-lock.json
  src/index.js
  src/navbar/index.js
  src/navbar/theme.scss
Labels: :art: design-update, :dart: 1.X Target

#156 ✨ (src/pages)-add landing page
  doc/package-lock.json
  doc/src/components/layout.js
  doc/src/components/styles.scss
  doc/src/components/theme.scss
  doc/src/images/chemistry.svg
  doc/src/images/code-image.svg
  doc/src/images/desktop.svg
  doc/src/images/engineer.svg
  doc/src/images/i-pad-air.svg
  doc/src/images/i-phone-6.svg
  doc/src/images/man-in-office-desk-with-computer.svg
  doc/src/images/match.svg
  doc/src/images/paint-board-and-brush.svg
  doc/src/images/quill-drawing-a-line.svg
  doc/src/images/tools.svg
  doc/src/images/triangle.svg
  doc/src/images/triple-arrow-merging-to-one.svg
  doc/src/pages/index.js
  doc/src/pages/index.scss
  doc/src/templates/landing-main/contrib-section/footer.js
  doc/src/templates/landing-main/contrib-section/index.js
  doc/src/templates/landing-main/contrib-section/index.scss
  doc/src/templates/landing-main/features.js
  doc/src/templates/landing-main/index.js
  doc/src/templates/landing-main/index.scss
  package-lock.json
  src/button/index.js
  src/button/theme.scss
  src/card/theme.scss
  src/navbar/theme.scss
Labels: :construction: WIP

#174 Docs page
  .eslintignore
  doc/package-lock.json
  doc/src/components/WithComponentsBar/Documentation.js
  doc/src/components/WithComponentsBar/WithComponentBar.js
  doc/src/components/WithComponentsBar/styles.scss
  doc/src/components/WithComponentsBar/tableTheme.scss
  doc/src/components/common/componentData/AutoComplete/index.js
  doc/src/components/common/componentData/Avatar/index.js
  doc/src/components/common/componentData/Badge/index.js
  doc/src/components/common/componentData/Button/index.js
  doc/src/components/common/componentData/Card/index.js
  doc/src/components/common/componentData/Carousel/index.js
  doc/src/components/common/componentData/Carousel/theme.scss
  doc/src/components/common/componentData/Checkbox/index.js
  doc/src/components/common/componentData/CheckboxGroup/index.js
  doc/src/components/common/componentData/Chip/index.js
  doc/src/components/common/componentData/Drawer/index.js
  doc/src/components/common/componentData/Menu/index.js
  doc/src/components/common/componentData/Modal/index.js
  doc/src/components/common/componentData/MultiSelect/index.js
  doc/src/components/common/componentData/Navbar/index.js
  doc/src/components/common/componentData/Popover/index.js
  doc/src/components/common/componentData/Preloader/index.js
  doc/src/components/common/componentData/ProgressBar/index.js
  doc/src/components/common/componentData/RadioButtonGroup/index.js
  doc/src/components/common/componentData/Select/index.js
  doc/src/components/common/componentData/Slider/index.js
  doc/src/components/common/componentData/Snackbar/index.js
  doc/src/components/common/componentData/Table/index.js
  doc/src/components/common/componentData/Table/theme.scss
  doc/src/components/common/componentData/TextInput/index.js
  doc/src/components/common/componentData/Toggle/index.js
  doc/src/components/common/componentData/Tooltip/index.js
  doc/src/components/common/componentData/index.js
  doc/src/components/common/componentData/theme.scss
  doc/src/components/common/componentList.js
  doc/src/components/common/styles.scss
  doc/src/pages/documentation.js
  docs/package-lock.json
  package-lock.json
  src/badge/index.js
  src/badge/theme.scss
  src/button/theme.scss
  src/drawer/index.js
  src/modal/index.js
  src/modal/tests/accessibility.test.js
  src/modal/tests/edgecases.test.js
  src/modal/tests/render.test.js
Labels: :art: design-update

#152 Table tests
  src/table/index.js
  src/table/tests/accessibility.test.js
  src/table/tests/render.test.js
Labels: :dart: 1.X Target

#196 Usage page fixes
  doc/src/components/WithComponentsBar/styles.scss
  doc/src/components/common/componentData/Avatar/index.js
  doc/src/components/common/componentData/Button/index.js
  doc/src/components/common/componentData/Checkbox/index.js
  doc/src/components/common/componentData/CheckboxGroup/index.js
  doc/src/components/common/componentData/Chip/index.js
  doc/src/components/common/componentData/Drawer/index.js
  doc/src/components/common/componentData/Popover/index.js
  doc/src/components/common/componentData/RadioButtonGroup/index.js
  doc/src/components/common/componentData/Snackbar/index.js
  doc/src/components/common/componentData/Table/index.js
  doc/src/components/common/componentData/TextInput/index.js
  doc/src/components/common/componentData/Toggle/index.js
  doc/src/components/common/componentData/Tooltip/index.js
  doc/src/components/usage/Usage.js
  doc/src/components/usage/styles.scss
Labels: :bug: bug

#195 Playground page
  doc/src/components/WithComponentsBar/WithComponentBar.js
  doc/src/components/common/componentData/Select/index.js
  doc/src/pages/documentation.js
  doc/src/pages/page-2.js
  doc/src/pages/playground.js
  doc/src/pages/playground.scss
  doc/src/pages/usage.js
  src/select/index.js
Labels: :construction: WIP

#150 change slider implementation
  src/slider/index.js
Labels: :dart: 1.X Target

#209 ✅ add render tests for slider component
  src/slider/index.js
  src/slider/tests/render.test.js
Labels: :dart: 1.X Target

#206 📝 Add readMe and docs for slider component
  doc/src/components/common/componentData/Slider/index.js
  src/slider/readMe.md
Labels: :dart: 1.X Target

#211 🐛 fix drawer width and height on small screens
  doc/src/pages/playground.js
  src/drawer/theme.scss
Labels: :bug: bug

#224 ✨ Switching between Usage and Documentation pages
  doc/gatsby-config.js
  doc/src/components/WithComponentsBar/WithComponentBar.js
  doc/src/components/WithComponentsBar/styles.scss
  doc/src/components/common/componentData/AutoComplete/index.js
  doc/src/components/common/componentData/Table/index.js
  doc/src/components/common/componentList.js
  doc/src/pages/404.js
  doc/src/pages/index.js
  doc/src/pages/playground.js
Labels: :sparkles: enhancement

#226 🐛 Fix sidebar height bug
  doc/src/components/WithComponentsBar/styles.scss
Labels: :bug: bug

#141 ✨ (src)-add pagination component
  doc/src/components/WithComponentsBar/styles.scss
  doc/src/components/common/componentData/Pagination/index.js
  doc/src/components/common/componentData/index.js
  doc/src/components/common/componentList.js
  src/index.js
  src/pagination/index.js
  src/pagination/readMe.md
  src/pagination/tests/accessibility.test.js
  src/pagination/tests/render.test.js
  src/pagination/theme.scss
Labels: :dart: 1.X Target

#250 Test coverage improvement
  lib/button/tests/render.test.js
  lib/card/index.js
  lib/card/tests/accessibility.test.js
  lib/card/tests/render.test.js
  lib/multiselect/index.js
  lib/multiselect/tests/accessibility.test.js
  lib/navbar/tests/accessibility.test.js
  lib/navbar/tests/edgecase.test.js
  lib/navbar/tests/render.test.js
  lib/popover/tests/edgecases.test.js
  lib/table/tests/accessibility.test.js
  package.json
Labels: :dart: 1.X Target

#255 Documentation page updates.
  doc/src/components/WithComponentsBar/styles.scss
  doc/src/components/WithComponentsBar/theme.module.scss
  doc/src/components/common/componentData/AutoComplete/index.js
  doc/src/components/common/componentData/AutoComplete/theme.scss
  doc/src/components/common/componentData/Button/index.js
  doc/src/components/common/componentData/MultiSelect/index.js
  doc/src/components/common/componentData/MultiSelect/theme.scss
  doc/src/components/common/componentData/Select/index.js
  doc/src/components/common/componentData/Select/theme.scss
  doc/src/components/header.js
  doc/src/components/styles.scss
  doc/src/components/usage/Usage.js
  doc/src/pages/index.js
  doc/src/pages/index.scss
  doc/src/templates/landing-main/contrib-section/footer.js
  doc/src/templates/landing-main/contrib-section/footer.module.scss
  doc/src/templates/landing-main/contrib-section/index.scss
  doc/src/templates/landing-main/index.scss
  lib/autocomplete/index.js
  lib/multiselect/index.js
  lib/select/index.js
Labels: Priority: High, Status: Completed, Type: Maintenance :hammer:

#252 Improve test coverage
  lib/autocomplete/tests/accessibility.test.js
  lib/autocomplete/tests/edgecases.test.js
  lib/drawer/tests/accessibility.test.js
  lib/navbar/index.js
  lib/navbar/tests/edgecase.test.js
  lib/pagination/tests/accessibility.test.js
  lib/select/index.js
  lib/select/tests/accessibility.test.js
  lib/snackbar/tests/render.test.js
  package.json
Labels: 1.X Target :dart:

#258 🐛 Fix expanded icon bug on Card
  lib/card/index.js
  package-lock.json
Labels: Type: Bug :bug:

#261 Minor fixes
  doc/src/components/common/componentData/Button/index.js
  doc/src/components/common/componentData/Pagination/index.js
  doc/src/components/common/componentData/Pagination/theme.scss
  doc/src/components/common/componentData/Toggle/index.js
  doc/src/components/common/componentData/theme.scss
  doc/src/pages/playground.scss
  doc/src/templates/landing-main/contrib-section/index.scss
  doc/src/templates/landing-main/index.scss
  lib/autocomplete/theme.module.scss
  lib/pagination/index.js
  package-lock.json
Labels: Type: Bug :bug:

#263 Development
  doc/src/components/WithComponentsBar/WithComponentBar.js
  doc/src/components/common/componentData/Button/index.js
  doc/src/components/common/componentData/Pagination/index.js
  doc/src/components/common/componentData/Pagination/theme.scss
  doc/src/components/common/componentData/Toggle/index.js
  doc/src/components/common/componentData/theme.scss
  doc/src/components/header.js
  doc/src/components/usage/Usage.js
  doc/src/pages/documentation.js
  doc/src/pages/index.js
  doc/src/pages/playground.js
  doc/src/pages/playground.scss
  doc/src/pages/usage.js
  doc/src/templates/landing-main/contrib-section/footer.js
  doc/src/templates/landing-main/contrib-section/index.scss
  doc/src/templates/landing-main/features.js
  doc/src/templates/landing-main/index.js
  doc/src/templates/landing-main/index.scss
  lib/autocomplete/index.js
  lib/autocomplete/tests/render.test.js
  lib/autocomplete/theme.module.scss
  lib/badge/index.js
  lib/button/index.js
  lib/card/index.js
  lib/carousel/carouselItem.js
  lib/carousel/index.js
  lib/carousel/tests/accessibility.test.js
  lib/checkbox/tests/accessibility.test.js
  lib/checkboxGroup/index.js
  lib/chip/index.js
  lib/drawer/index.js
  lib/drawer/tests/accessibility.test.js
  lib/drawer/tests/render.test.js
  lib/examples/card.js
  lib/modal/tests/edgecases.test.js
  lib/modal/tests/render.test.js
  lib/multiselect/index.js
  lib/multiselect/tests/render.test.js
  lib/navbar/index.js
  lib/pagination/index.js
  lib/popover/tests/edgecases.test.js
  lib/progressbar/index.js
  lib/radioButtonGroup/index.js
  lib/select/index.js
  lib/select/tests/render.test.js
  lib/slider/index.js
  lib/snackbar/index.js
  lib/snackbar/tests/render.test.js
  lib/table/index.js
  lib/textInput/tests/accessibility.test.js
  lib/toggle/index.js
  lib/toggle/tests/accessibility.test.js
  lib/tooltip/index.js
  package-lock.json
  package.json
  webpack.common.js
  webpack.prod.js
Labels: Status: On Hold :hand:

#269 🚑 Fix broken links on usage and documentation page
  doc/src/components/WithComponentsBar/WithComponentBar.js
  doc/src/components/WithComponentsBar/styles.scss
Labels: Priority: Critical :grey_exclamation:, Type: Bug :bug:

#268 Release automation
  .travis.yml
  package-lock.json
  package.json
Labels: Priority: High, Status: On Hold :hand:, Type: Enhancement :sparkles:

#271 🔧 netlify deploy fix attempt
  netlify.toml
Labels: Priority: High, Type: Bug :bug:

#275 🐛 Fix scroll and type bug on auto complete
  doc/package-lock.json
  lib/autocomplete/index.js
  lib/autocomplete/theme.module.scss
Labels: Priority: Critical :grey_exclamation:, Type: Bug :bug:

#266 Development
  .travis.yml
  CHANGELOG.md
  README.md
  doc/gatsby-browser.js
  doc/gatsby-config.js
  doc/package-lock.json
  doc/package.json
  doc/src/components/WithComponentsBar/WithComponentBar.js
  doc/src/components/WithComponentsBar/styles.scss
  doc/src/components/common/componentData/Drawer/index.js
  doc/src/components/layout.js
  doc/src/pages/404.js
  lib/autocomplete/index.js
  lib/autocomplete/theme.module.scss
  netlify.toml
  package-lock.json
  package.json
Labels: Status: On Hold :hand:, Type: Maintenance :hammer:

#280 chore(readme.md): update readme badges.
  README.md
Labels: Type: Maintenance :hammer:
