Repository Codebrahma/react-lite-ui, pull requests merged in 2019-01, with the labels that each got.

#299 fix(customscroll): reduce custom scroll width and add radius
  lib/globals/common.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, Status: Completed, design-update :art:

#288 fix(autocomplete): update autocomplete design
  lib/autocomplete/index.js
  lib/autocomplete/tests/edgecases.test.js
  lib/autocomplete/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, design-update :art:

#289 style(Badge): Update Badge position
  lib/badge/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, design-update :art:

#291 fix(Checkbox): Fix checkbox design bugs
  doc/src/components/common/componentData/Checkbox/theme.scss
  lib/checkbox/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, design-update :art:

#292 fix(RadioButtonGroup): Fix RadioButtonGroup design bugs
  lib/radioButtonGroup/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, design-update :art:

#294 fix(Snackbar): fix snackbar positioning and responsiveness
  doc/src/components/common/componentData/Snackbar/index.js
  lib/snackbar/index.js
  lib/snackbar/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, design-update :art:

#296 Multiselect design update
  lib/globals/animations.module.scss
  lib/multiselect/index.js
  lib/multiselect/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, Type: Bug :bug:, design-update :art:

#297 Navbar design updates
  doc/src/components/common/componentData/Navbar/index.js
  lib/navbar/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, design-update :art:

#300 Table design update
  doc/src/components/common/componentData/Table/index.js
  lib/table/index.js
  lib/table/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, design-update :art:

#301 Button shadow changes
  lib/button/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, design-update :art:

#302 fix(preloader): fix preloader animation
  lib/preloader/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, Status: Completed, design-update :art:

#298 popover design updates
  lib/popover/index.js
  lib/popover/tests/accessibility.test.js
  lib/popover/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, Status: Completed, design-update :art:

#303 fix(Pagination): fix width and add animations
  doc/src/components/common/componentData/Pagination/index.js
  lib/pagination/index.js
  lib/pagination/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, design-update :art:

#295 Modal design update
  lib/globals/fonts.scss
  lib/modal/index.js
  lib/modal/tests/accessibility.test.js
  lib/modal/tests/render.test.js
  lib/modal/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, Status: Completed, design-update :art:

#305 Tooltip design update
  lib/tooltip/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, Status: Completed, design-update :art:

#304 Select design updates
  lib/select/index.js
  lib/select/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, design-update :art:

#306 Progressbar design updates
  lib/progressbar/index.js
  lib/progressbar/tests/accessibility.test.js
  lib/progressbar/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, design-update :art:

#293 fix(chip): fix chip component design
  lib/avatar/theme.module.scss
  lib/chip/index.js
  lib/chip/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, design-update :art:

#290 Card design update
  lib/card/index.js
  lib/card/tests/render.test.js
  lib/card/theme.module.scss
Labels: Priority: High, Status: Accepted :white_check_mark:, design-update :art:

#308 fix(carousel): add shadow on hover
  doc/package-lock.json
  doc/src/components/common/componentData/Carousel/index.js
  lib/carousel/index.js
  lib/carousel/readMe.md
  lib/carousel/tests/render.test.js
  lib/carousel/theme.module.scss
  package-lock.json
Labels: Priority: High, Status: Accepted :white_check_mark:, design-update :art:

#309 fix(textinput): fix input width
  lib/textInput/theme.module.scss
Labels: Priority: High, Status: Review Needed :mag_right:

#319 fix(pages): fix window.gtag issue on local
  package-lock.json
  src/pages/documentation.jsx
  src/pages/index.jsx
  src/pages/playground.jsx
  src/pages/usage.jsx
Labels: Type: Bug :bug:
